### ISSUE TITLE
Implement base layout

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/floripamais#5]
## Description 

Implement base layout components, such as header and footer. 

## Tasks 

- [x] Implement Header 

- [x] Implement Footer 

## Notes

Be aware to show the organization social media

**Comment by betofigueiredo** [comment]
Oi @LauraBeatris, tudo bem? Já existe o layout do projeto? Se precisar posso ajudar no design ou no desenvolvimento. Abs

**Comment by LauraBeatris** [comment]
@betofigueiredo Oi Beto 

Existe layout mas não posso deixar público pois a organização que decide sobre isso. Valeu pela disponibilidade 😄
